version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      TEST_LOGSTASH_URL: 'logstash:9600' # Logstash 서비스 URL 업데이트
    command: npm run test:ci
    depends_on:
      - logstash
  logstash:
    image: 'logstash:8.13.0'
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./drivers:/usr/share/logstash/drivers
    ports:
      - '9600:9600' # 필요한 경우 외부 포트 노출
