version: '3.7'
services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  redis-0:
    image: redis:latest
    command: >
      sh -c "
        redis-server --appendonly yes --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --port 6380;
        sleep 10;
        redis-cli --cluster check 172.20.0.2:6380;
      "
    ports:
      - '6380:6380'
    networks:
      redis-cluster-net:
        ipv4_address: 172.20.0.2
    volumes:
      - redis-0-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
  redis-1:
    image: redis:latest
    command: >
      sh -c "
        redis-server --appendonly yes --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --port 6381;
        sleep 10;
        redis-cli --cluster check 172.20.0.3:6381;
      "
    ports:
      - '6381:6381'
    networks:
      redis-cluster-net:
        ipv4_address: 172.20.0.3
    volumes:
      - redis-1-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
  redis-2:
    image: redis:latest
    command: >
      sh -c "
        redis-server --appendonly yes --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --port 6382;
        sleep 10;
        redis-cli --cluster check 172.20.0.4:6382;
      "
    ports:
      - '6382:6382'
    networks:
      redis-cluster-net:
        ipv4_address: 172.20.0.4
    volumes:
      - redis-2-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
  redis-3:
    image: redis:latest
    command: >
      sh -c "
        redis-server --appendonly yes --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --port 6383;
        sleep 10;
        redis-cli --cluster check 172.20.0.5:6383;
      "
    ports:
      - '6383:6383'
    networks:
      redis-cluster-net:
        ipv4_address: 172.20.0.5
    volumes:
      - redis-3-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
  redis-4:
    image: redis:latest
    command: >
      sh -c "
        redis-server --appendonly yes --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --port 6384;
        sleep 10;
        redis-cli --cluster check 172.20.0.6:6384;
      "
    ports:
      - '6384:6384'
    networks:
      redis-cluster-net:
        ipv4_address: 172.20.0.6
    volumes:
      - redis-4-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
  redis-5:
    image: redis:latest
    command: >
      sh -c "
        redis-server --appendonly yes --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --port 6385;
        sleep 10;
        redis-cli --cluster check 172.20.0.7:6385;
      "
    ports:
      - '6385:6385'
    networks:
      redis-cluster-net:
        ipv4_address: 172.20.0.7
    volumes:
      - redis-5-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
  redis-cluster-init:
    image: redis:latest
    depends_on:
      - redis-0
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
    command: >
      sh -c "
        sleep 20;
        redis-cli --cluster create 172.20.0.2:6380 172.20.0.3:6381 172.20.0.4:6382 172.20.0.5:6383 172.20.0.6:6384 172.20.0.7:6385 --cluster-replicas 1 --cluster-yes;
      "
    networks:
      - redis-cluster-net
networks:
  redis-cluster-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
volumes:
  postgres-data:
  redis-0-data:
  redis-1-data:
  redis-2-data:
  redis-3-data:
  redis-4-data:
  redis-5-data:
