name: testAndDeploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: CheckOut repository
        uses: actions/checkout@v3
      - name: Build and test with Docker Compose
        run: docker-compose -f docker-compose.yaml up --build --abort-on-container-exit
  deploy:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::767398029720:role/githubKimsungmin2_nest_OIDC
          role-session-name: sampleSessionName
          aws-region: ${{ env.AWS_REGION }}
